### YamlMime:PythonClass
uid: azure.ai.ml.exceptions.ValidationException
name: ValidationException
fullName: azure.ai.ml.exceptions.ValidationException
module: azure.ai.ml.exceptions
inheritances:
- azure.ai.ml.exceptions.MlException
summary: Class for all exceptions raised as part of client-side schema validation.
constructor:
  syntax: 'ValidationException(message: str, no_personal_data_message: str, *args,
    error_type: azure.ai.ml.exceptions.ValidationErrorType = <ValidationErrorType.GENERIC:
    ''GENERIC''>, target: azure.ai.ml.exceptions.ErrorTarget = ''Unknown'', error_category:
    azure.ai.ml.exceptions.ErrorCategory = ''UserError'', **kwargs)'
  parameters:
  - name: message
    description: A message describing the error. This is the error message the user
      will see.
    isRequired: true
    types:
    - <xref:str>
  - name: no_personal_data_message
    description: 'The error message without any personal data.

      This will be pushed to telemetry logs.'
    isRequired: true
    types:
    - <xref:str>
  - name: error_type
    description: The error type, chosen from one of the values of ValidationErrorType
      enum class.
    isRequired: true
    types:
    - <xref:azure.ai.ml.exceptions.ValidationErrorType>
  - name: target
    description: The name of the element that caused the exception to be thrown.
    isRequired: true
    types:
    - <xref:azure.ai.ml.exceptions.ErrorTarget>
  - name: error_category
    description: The error category, defaults to Unknown.
    isRequired: true
    types:
    - <xref:azure.ai.ml.exceptions.ErrorCategory>
  - name: error
    description: The original exception if any.
    isRequired: true
    types:
    - <xref:Exception>
attributes:
- uid: azure.ai.ml.exceptions.ValidationException.error_type
  name: error_type
  summary: Return the error type.
  return:
    description: The error type.
    types:
    - <xref:azure.ai.ml.exceptions.ValidationErrorType>
